
ppb_default: tasks


ppb_tasks:
	@perl ./t/res/PPBFile --tasks

ppb_clear_session:
	@rm -f .session

ppb_TaskA: ppb_clear_session
	@perl ./t/res/PPBFile --session .session TaskA

ppb_TaskB: ppb_clear_session
	@perl ./t/res/PPBFile --session .session TaskB

