
default: tasks


tasks:
	@perl ./t/res/PPBFile --tasks

clear_session:
	@rm -f .session

TaskA: clear_session
	@perl ./t/res/PPBFile --session .session TaskA

TaskB: clear_session
	@perl ./t/res/PPBFile --session .session TaskB

