---
abstract: 'Perl Project Build System, The low-learning curve simple build system.'
author:
  - 'Chad Granum <exodist7@gmail.com>'
build_requires:
  Test::Exception: 0.27
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-PPBuild
no_index:
  directory:
    - inc
    - t
requires:
  Exporter: 5.63
  YAML::Syck: 1.05
version: 0.11
